<script setup lang="ts">
import type { TaskCard } from '~/types/task';
const route = useRoute(); const platform = usePlatformApi(); const { role, setRole } = useRole(); const id = String(route.params.id);
const { data: task, pending, error: loadError, refresh: reload } = await useAsyncData(`task-${id}`, () => platform.getTask(id));
const refresh = () => reload();
const form = reactive<TaskCard>({ title:'', topic:'', context:'', need:'', users:'', data:'', constraints:'', expectedResult:'', successCriteria:'', contact:'', interactionFormat:'' });
watch(task, value => { if (value) Object.assign(form, value.card); }, { immediate: true });
const missingLabels: Record<string, string> = { title: 'Название', topic: 'Тема', context: 'Контекст', need: 'Потребность', users: 'Пользователи', data: 'Данные и материалы', constraints: 'Ограничения', expected_result: 'Ожидаемый результат', success_criteria: 'Критерии успеха', contact: 'Контакт', interaction_format: 'Формат взаимодействия' };
const saving = ref(false); const message = ref(''); const actionError = ref('');
const fields = [{key:'topic',label:'Тема'},{key:'context',label:'Контекст'},{key:'need',label:'Потребность'},{key:'users',label:'Пользователи'},{key:'data',label:'Данные и материалы'},{key:'constraints',label:'Ограничения'},{key:'expectedResult',label:'Ожидаемый результат'},{key:'successCriteria',label:'Критерии успеха'},{key:'contact',label:'Контакт'},{key:'interactionFormat',label:'Формат взаимодействия'}] as const;
async function save() { saving.value=true; actionError.value=''; try { task.value = await platform.updateTask(id, Object.fromEntries(Object.entries(form).map(([key,value]) => [key,value.trim()])) as unknown as TaskCard); message.value='Изменения сохранены'; } catch(cause) { actionError.value=cause instanceof Error?cause.message:'Ошибка сохранения'; } finally { saving.value=false; } }
async function confirm() { await save(); if (actionError.value) return; saving.value=true; try { task.value=await platform.confirmTask(id); message.value='Карточка подтверждена'; } catch(cause) { actionError.value=cause instanceof Error?cause.message:'Ошибка подтверждения'; } finally { saving.value=false; } }
async function publish() { if (task.value?.status==='draft') await confirm(); if (actionError.value) return; saving.value=true; try { task.value=await platform.publishTask(id); await navigateTo(`/catalog/${id}`); } catch(cause) { actionError.value=cause instanceof Error?cause.message:'Ошибка публикации'; } finally { saving.value=false; } }
useHead({ title:'Карточка задачи — Мост' });
</script>
<template><div class="page"><NuxtLink to="/tasks" class="back-link">К моим задачам</NuxtLink><p v-if="pending">Загружаем карточку…</p><p v-else-if="loadError" class="error-text">Не удалось загрузить задачу. <button @click="refresh">Повторить</button></p><template v-else-if="task && role==='business'"><div class="page-heading"><div><h1>Редактор карточки<span class="heading-dot">.</span></h1></div><span class="badge">{{ task.status === 'published' ? 'Опубликована' : task.status === 'confirmed' ? 'Подтверждена' : 'Не опубликована' }}</span></div><form class="form-layout editor-layout" @submit.prevent="publish"><div class="panel editor-panel"><label class="field"><span>Название *</span><input v-model="form.title" required></label><label v-for="field in fields" :key="field.key" class="field"><span>{{ field.label }}</span><textarea v-model="form[field.key]" rows="3" /></label></div><aside class="editor-sidebar"><div class="panel score-panel"><ReadinessScore :score="task.score" :breakdown="task.breakdown" detailed /><p class="readiness-note">Оценка сохранённой карточки. Сохраните и подтвердите описание для пересчёта.</p><div v-if="task.missingInformation.length"><h3>Не хватает</h3><ul><li v-for="item in task.missingInformation" :key="item">{{ missingLabels[item] || item }}</li></ul></div><div v-if="task.suggestions.length"><h3>Как улучшить</h3><ul><li v-for="item in task.suggestions" :key="item">{{ item }}</li></ul></div></div><div class="panel publish-panel"><button type="button" class="button button-outline button-full" :disabled="saving" @click="save">Сохранить</button><button v-if="task.status==='draft'" type="button" class="button button-outline button-full" :disabled="saving" @click="confirm">Подтвердить карточку</button><button v-if="task.status!=='published'" class="button button-primary button-full" :disabled="saving">Опубликовать</button><p v-if="message" class="success-inline">{{ message }}</p><p v-if="actionError" class="error-text">{{ actionError }}</p></div></aside></form></template><EmptyState v-else-if="role!=='business'" title="Редактирование доступно бизнесу" description="Переключитесь в роль бизнеса."><button class="button button-primary" @click="setRole('business')">Перейти в роль бизнеса</button></EmptyState></div></template>
