<script setup lang="ts">
const { t } = useLocale();

const props = defineProps<{ taskId: string }>(); const platform = usePlatformApi(); const { selectedTeamId } = useRole();
const { data: teams, pending: teamsPending, error: teamsError } = await useAsyncData('proposal-teams', platform.listTeams);
watchEffect(() => { if (!selectedTeamId.value && teams.value?.[0]) selectedTeamId.value = teams.value[0].id; });
const sent = ref(false); const loading = ref(false); const error = ref('');
const form = reactive({ idea: '', plan: '', timeframe: '', prototypeUrl: '' });
async function submit() { if (!selectedTeamId.value) return; loading.value = true; error.value = ''; try { await platform.createProposal(props.taskId, { teamId: selectedTeamId.value, ...form, prototypeUrl: form.prototypeUrl.trim() || undefined }); sent.value = true; } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Не удалось отправить предложение'; } finally { loading.value = false; } }
const selectedTeam = computed(() => teams.value?.find(team => team.id === selectedTeamId.value));
</script>
<template><div v-if="sent" class="proposal-success" role="status"><span class="success-symbol"><AppIcon name="check" :size="30" /></span><h2>{{ t("Предложение отправлено") }}</h2><p>{{ t("Статус появится в разделе ваших предложений.") }}</p><NuxtLink to="/proposals" class="button button-primary">{{ t("Мои предложения") }}</NuxtLink></div><form v-else class="proposal-form" @submit.prevent="submit"><span class="eyebrow"><AppIcon name="send" :size="14" />{{ t("ОТКЛИК НА ЗАДАЧУ") }}</span><h2>{{ t("Предложите решение.") }}</h2><p class="form-intro">{{ t("Опишите идею, основные шаги и реалистичный срок.") }}</p><div class="selected-team" role="status"><span class="team-avatar"><AppIcon name="users" :size="18" /></span><div><small>{{ t("Предложение от команды") }}</small><strong>{{ teamsPending ? t("Загружаем команду…") : selectedTeam?.name || t("Команда не выбрана") }}</strong></div><span>{{ t("Меняется в верхней панели") }}</span></div><p v-if="teamsError" class="error-text" role="alert">{{ t("Не удалось загрузить команды") }}</p><label class="field"><span>{{ t("Ваша идея") }} <span class="required">*</span></span><textarea v-model="form.idea" required minlength="10" rows="4" :placeholder="t('Как вы предлагаете решить задачу?')" /></label><label class="field"><span>{{ t("Краткий план") }} <span class="required">*</span></span><textarea v-model="form.plan" required minlength="10" rows="3" :placeholder="t('Перечислите основные этапы')" /></label><div class="form-two-columns"><label class="field"><span>{{ t("Предполагаемый срок") }} <span class="required">*</span></span><input v-model="form.timeframe" required :placeholder="t('Например, 6 недель')"></label><label class="field"><span>{{ t("Ссылка на прототип") }}</span><input v-model="form.prototypeUrl" type="url" placeholder="https://"></label></div><p v-if="error" class="error-text" role="alert">{{ t(error) }}</p><div class="form-actions"><span class="form-assurance"><AppIcon name="shield" :size="15" />{{ t("Бизнес увидит данные вашей команды") }}</span><button class="button button-primary" :disabled="loading || !selectedTeamId"><AppIcon name="send" :size="16" />{{ loading ? t("Отправляем…") : t("Отправить предложение") }}</button></div></form></template>
