<script setup lang="ts">
const props = defineProps<{ taskId: string }>(); const platform = usePlatformApi(); const { selectedTeamId } = useRole();
const { data: teams, error: teamsError } = await useAsyncData('proposal-teams', platform.listTeams);
watchEffect(() => { if (!selectedTeamId.value && teams.value?.[0]) selectedTeamId.value = teams.value[0].id; });
const sent = ref(false); const loading = ref(false); const error = ref('');
const form = reactive({ idea: '', plan: '', timeframe: '', prototypeUrl: '' });
async function submit() { if (!selectedTeamId.value) return; loading.value = true; error.value = ''; try { await platform.createProposal(props.taskId, { teamId: selectedTeamId.value, ...form, prototypeUrl: form.prototypeUrl.trim() || undefined }); sent.value = true; } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Не удалось отправить предложение'; } finally { loading.value = false; } }
</script>
<template><div v-if="sent" class="proposal-success"><h2>Предложение отправлено!</h2><p>Статус появится в разделе ваших предложений.</p><NuxtLink to="/proposals" class="button button-primary">Мои предложения</NuxtLink></div><form v-else class="proposal-form" @submit.prevent="submit"><h2>Давайте знакомиться.</h2><label class="field"><span>Команда</span><select v-model="selectedTeamId" required><option value="" disabled>Выберите команду</option><option v-for="team in teams || []" :key="team.id" :value="team.id">{{ team.name }}</option></select></label><p v-if="teamsError" class="error-text">Не удалось загрузить команды</p><label class="field"><span>Ваша идея *</span><textarea v-model="form.idea" required minlength="10" rows="4" /></label><label class="field"><span>Краткий план *</span><textarea v-model="form.plan" required minlength="10" rows="3" /></label><div class="form-two-columns"><label class="field"><span>Предполагаемый срок *</span><input v-model="form.timeframe" required></label><label class="field"><span>Ссылка на прототип</span><input v-model="form.prototypeUrl" type="url" placeholder="https://"></label></div><p v-if="error" class="error-text">{{ error }}</p><div class="form-actions"><button class="button button-primary" :disabled="loading || !selectedTeamId">{{ loading ? 'Отправляем…' : 'Отправить предложение' }}</button></div></form></template>
