<script setup lang="ts">
const props = defineProps<{ taskId: string }>(); const platform = usePlatformApi(); const { selectedTeamId } = useRole();
const { data: teams, pending: teamsPending, error: teamsError } = await useAsyncData('proposal-teams', platform.listTeams);
watchEffect(() => { if (!selectedTeamId.value && teams.value?.[0]) selectedTeamId.value = teams.value[0].id; });
const sent = ref(false); const loading = ref(false); const error = ref('');
const form = reactive({ idea: '', plan: '', timeframe: '', prototypeUrl: '' });
async function submit() { if (!selectedTeamId.value) return; loading.value = true; error.value = ''; try { await platform.createProposal(props.taskId, { teamId: selectedTeamId.value, ...form, prototypeUrl: form.prototypeUrl.trim() || undefined }); sent.value = true; } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Не удалось отправить предложение'; } finally { loading.value = false; } }
const selectedTeam = computed(() => teams.value?.find(team => team.id === selectedTeamId.value));
</script>
<template><div v-if="sent" class="proposal-success" role="status"><span class="success-symbol"><AppIcon name="check" :size="30" /></span><h2>Предложение отправлено</h2><p>Статус появится в разделе ваших предложений.</p><NuxtLink to="/proposals" class="button button-primary">Мои предложения</NuxtLink></div><form v-else class="proposal-form" @submit.prevent="submit"><span class="eyebrow"><AppIcon name="send" :size="14" />ОТКЛИК НА ЗАДАЧУ</span><h2>Предложите решение.</h2><p class="form-intro">Опишите идею, основные шаги и реалистичный срок.</p><div class="selected-team" role="status"><span class="team-avatar"><AppIcon name="users" :size="18" /></span><div><small>Предложение от команды</small><strong>{{ teamsPending ? 'Загружаем команду…' : selectedTeam?.name || 'Команда не выбрана' }}</strong></div><span>Меняется в верхней панели</span></div><p v-if="teamsError" class="error-text" role="alert">Не удалось загрузить команды</p><label class="field"><span>Ваша идея <span class="required">*</span></span><textarea v-model="form.idea" required minlength="10" rows="4" placeholder="Как вы предлагаете решить задачу?" /></label><label class="field"><span>Краткий план <span class="required">*</span></span><textarea v-model="form.plan" required minlength="10" rows="3" placeholder="Перечислите основные этапы" /></label><div class="form-two-columns"><label class="field"><span>Предполагаемый срок <span class="required">*</span></span><input v-model="form.timeframe" required placeholder="Например, 6 недель"></label><label class="field"><span>Ссылка на прототип</span><input v-model="form.prototypeUrl" type="url" placeholder="https://"></label></div><p v-if="error" class="error-text" role="alert">{{ error }}</p><div class="form-actions"><span class="form-assurance"><AppIcon name="shield" :size="15" />Бизнес увидит данные вашей команды</span><button class="button button-primary" :disabled="loading || !selectedTeamId"><AppIcon name="send" :size="16" />{{ loading ? 'Отправляем…' : 'Отправить предложение' }}</button></div></form></template>
