<script setup lang="ts">
import type { ProposalStatus } from '~/types/task';
const props = defineProps<{ taskId?: string }>(); const platform = usePlatformApi(); const { role, selectedTeamId } = useRole();
const status = ref('all'); const changing = ref('');
const { data: proposals, pending, error, refresh } = await useAsyncData(() => `proposals-${props.taskId || 'all'}`, () => platform.listProposals(props.taskId));
const visible = computed(() => (proposals.value || []).filter(item => (role.value !== 'team' || item.teamId === selectedTeamId.value) && (status.value === 'all' || item.status === status.value)));
const statuses = [{ key: 'all', label: 'Все' }, { key: 'pending', label: 'На рассмотрении' }, { key: 'accepted', label: 'Принятые' }, { key: 'rejected', label: 'Отклонённые' }];
async function decide(id: string, next: Exclude<ProposalStatus, 'pending'>) { changing.value = id; try { await platform.updateProposal(id, next); await refresh(); } finally { changing.value = ''; } }
</script>
<template><div><div class="filter-tabs"><button v-for="item in statuses" :key="item.key" :class="{ active: status === item.key }" @click="status = item.key">{{ item.label }}</button></div><p v-if="pending">Загружаем предложения…</p><p v-else-if="error" class="error-text">Не удалось загрузить предложения.</p><div v-else-if="visible.length" class="proposal-list"><article v-for="proposal in visible" :key="proposal.id" class="panel proposal-card"><div class="proposal-card-heading"><span class="team-avatar">{{ proposal.team.slice(0, 2).toUpperCase() }}</span><div><h2>{{ proposal.team }}</h2><NuxtLink :to="`/catalog/${proposal.taskId}`">Открыть задачу</NuxtLink></div><span class="badge">{{ proposal.status }}</span></div><div class="proposal-content"><div><h3>Идея решения</h3><p>{{ proposal.idea }}</p></div><div><h3>План команды</h3><p>{{ proposal.plan }}</p></div></div><div class="proposal-card-bottom"><span>{{ proposal.timeframe }}</span><div v-if="role === 'business' && proposal.status === 'pending'" class="proposal-actions"><button class="button button-outline button-small" :disabled="changing === proposal.id" @click="decide(proposal.id, 'rejected')">Отклонить</button><button class="button button-primary button-small" :disabled="changing === proposal.id" @click="decide(proposal.id, 'accepted')">Принять</button></div></div></article></div><EmptyState v-else title="Предложений пока нет" description="Здесь появятся предложения выбранной команды или отклики на задачу." /></div></template>
