<script setup lang="ts">
const platform = usePlatformApi(); const { role, setRole } = useRole(); const status = ref('all');
const { data: tasks, pending, error, refresh: reload } = await useAsyncData('business-tasks', () => platform.listTasks(true)); const refresh = () => reload();
const filters = [{key:'all',label:'Все'},{key:'published',label:'Опубликованные'},{key:'confirmed',label:'Подтверждённые'},{key:'draft',label:'Черновики'}];
const visible = computed(() => (tasks.value || []).filter(task => status.value === 'all' || task.status === status.value));
const count = (key: string) => key === 'all' ? tasks.value?.length || 0 : tasks.value?.filter(task => task.status === key).length || 0;
onActivated(refresh); useHead({ title: 'Мои задачи — Мост' });
</script>
<template><div class="page"><div class="page-heading"><div><span class="eyebrow"><AppIcon name="layers" :size="14" />РАБОЧЕЕ ПРОСТРАНСТВО БИЗНЕСА</span><h1>Мои задачи<span class="heading-dot">.</span></h1><p>Управляйте карточками от первого наброска до публикации.</p></div><NuxtLink v-if="role === 'business'" to="/tasks/new" class="button button-primary"><AppIcon name="plus" :size="17" />Новая задача</NuxtLink></div><template v-if="role === 'business'"><div class="catalog-tabs-row"><div class="filter-tabs" role="group" aria-label="Фильтр задач"><button v-for="item in filters" :key="item.key" :class="{ active: status === item.key }" :aria-pressed="status === item.key" @click="status = item.key">{{ item.label }} <span>{{ count(item.key) }}</span></button></div></div><div v-if="pending" class="state-panel" role="status"><span class="state-icon"><AppIcon name="layers" /></span><div><strong>Загружаем ваши задачи</strong><p>Проверяем актуальные статусы карточек.</p></div></div><div v-else-if="error" class="state-panel state-error" role="alert"><span class="state-icon"><AppIcon name="info" /></span><div><strong>Не удалось загрузить задачи</strong><button class="text-link" @click="refresh">Попробовать снова</button></div></div><div v-else-if="visible.length" class="task-grid tasks-management"><TaskCard v-for="task in visible" :key="task.id" :task="task" manage /></div><EmptyState v-else title="Задач пока нет" description="Создайте первую задачу, а AI поможет превратить идею в понятную карточку."><NuxtLink to="/tasks/new" class="button button-primary">Создать задачу</NuxtLink></EmptyState></template><EmptyState v-else title="Раздел бизнеса" description="Переключитесь в роль бизнеса, чтобы управлять задачами."><button class="button button-primary" @click="setRole('business')">Перейти в роль бизнеса</button></EmptyState></div></template>
