<script setup lang="ts">
const { t } = useLocale();

const route=useRoute(); const platform=usePlatformApi(); const {role,setRole}=useRole(); const id=String(route.params.id);
const {data:task,pending,error,refresh:reload}=await useAsyncData(`catalog-task-${id}`,()=>platform.getTask(id)); const refresh=()=>reload();
const sections=computed(()=>task.value?[{label:'Контекст',value:task.value.card.context,icon:'building'},{label:'Потребность',value:task.value.card.need,icon:'target'},{label:'Пользователи',value:task.value.card.users,icon:'users'},{label:'Данные и материалы',value:task.value.card.data,icon:'file'},{label:'Ограничения',value:task.value.card.constraints,icon:'shield'},{label:'Ожидаемый результат',value:task.value.card.expectedResult,icon:'sparkles'},{label:'Критерии успеха',value:task.value.card.successCriteria,icon:'check'},{label:'Контакт',value:task.value.card.contact,icon:'message'},{label:'Формат взаимодействия',value:task.value.card.interactionFormat,icon:'clock'}]:[]);
useHead(() => ({ title: t("Задача — Мост") }));
</script>
<template><div class="page"><NuxtLink to="/catalog" class="back-link"><AppIcon name="back" :size="15" />{{ t("В каталог задач") }}</NuxtLink><div v-if="pending" class="state-panel" role="status"><span class="state-icon"><AppIcon name="file" /></span><div><strong>{{ t("Загружаем задачу") }}</strong><p>{{ t("Собираем карточку и рейтинг готовности.") }}</p></div></div><div v-else-if="error" class="state-panel state-error" role="alert"><span class="state-icon"><AppIcon name="info" /></span><div><strong>{{ t("Не удалось загрузить задачу") }}</strong><button class="text-link" @click="refresh">{{ t("Попробовать снова") }}</button></div></div><template v-else-if="task && task.status==='published'"><div class="detail-heading"><div class="detail-company"><span class="company-icon tone-blue"><AppIcon name="briefcase" /></span><div><strong>{{ t("Задача бизнеса") }}</strong><span>{{ t("Открыта для предложений") }}</span></div><span class="badge badge-success"><span class="status-dot" />{{ taskStatusLabel(task.status) }}</span></div><h1>{{ task.card.title || t("Задача без названия") }}</h1><span class="tag">{{ topicLabel(task.card.topic) }}</span></div><div class="detail-layout"><div class="detail-main"><article class="panel task-full-card"><section v-for="section in sections" :key="section.label" class="detail-section"><h2><AppIcon :name="section.icon" />{{ t(section.label) }}</h2><p :class="{ 'missing-value': !section.value }">{{ section.value || t("Информация пока не указана") }}</p></section></article><section class="panel proposal-form-panel"><ProposalForm v-if="role==='team'" :task-id="task.id" /><div v-else class="role-invite"><span class="empty-icon"><AppIcon name="users" :size="28" /></span><h2>{{ t("Есть идея решения?") }}</h2><p>{{ t("Переключитесь на роль команды и расскажите бизнесу о своём подходе.") }}</p><button class="button button-primary" @click="setRole('team')"><AppIcon name="users" :size="16" />{{ t("Я представляю команду") }}</button></div></section></div><aside class="detail-sidebar"><div class="panel score-panel"><span class="eyebrow">{{ t("ГОТОВНОСТЬ К СТАРТУ") }}</span><ReadinessScore :score="task.score" /><p>{{ t("Рейтинг показывает, насколько подробно бизнес описал вводные задачи.") }}</p></div><div class="aside-note"><AppIcon name="info" /><h3>{{ t("Перед откликом") }}</h3><p>{{ t("Проверьте ожидания, ограничения и формат взаимодействия.") }}</p></div></aside></div></template><EmptyState v-else :title="t('Задача не найдена')" :description="t('Она не опубликована или была удалена.')" /></div></template>
