<script setup lang="ts">
const { t } = useLocale();

const platform = usePlatformApi(); const search = ref(''); const topic = ref(''); const level = ref('all'); const sort = ref('desc');
const { data: tasks, pending, error, refresh: reload } = await useAsyncData('catalog-tasks', () => platform.listTasks());
const refresh = () => reload();
const topics = computed(() => [...new Set((tasks.value || []).map(task => task.card.topic).filter(Boolean))]);
const levels = ['draft','workable','ready','priority'];
const filtered = computed(() => { const q = search.value.trim().toLowerCase(); const result = (tasks.value || []).filter(task => (!topic.value || task.card.topic === topic.value) && (level.value === 'all' || task.score.level === level.value) && (!q || Object.values(task.card).join(' ').toLowerCase().includes(q))); return result.sort((a,b) => sort.value === 'asc' ? a.score.total-b.score.total : sort.value === 'new' ? Date.parse(b.createdAt)-Date.parse(a.createdAt) : b.score.total-a.score.total); });
useHead(() => ({ title: t("Каталог задач — Мост") }));
</script>
<template><div class="page"><div class="page-heading"><div><span class="eyebrow"><AppIcon name="compass" :size="14" />{{ t("КАТАЛОГ ВОЗМОЖНОСТЕЙ") }}</span><h1>{{ t("Задачи, которые ждут") }} <span>{{ t("вас.") }}</span></h1><p>{{ t("Настоящие вызовы бизнеса для студенческих команд.") }}</p></div></div><div class="catalog-callout"><span class="callout-icon"><AppIcon name="sparkles" /></span><div><strong>{{ t("Выберите задачу по интересам и готовности") }}</strong><p>{{ t("Чем выше готовность, тем больше вводных уже собрано для старта.") }}</p></div><span class="callout-decoration">✳</span></div><div class="catalog-toolbar"><label class="search-field"><AppIcon name="search" :size="18" /><span class="sr-only">{{ t("Поиск задач") }}</span><input v-model="search" type="search" :placeholder="t('Поиск по задачам')"></label><label class="select-field"><AppIcon name="filter" :size="16" /><span class="sr-only">{{ t("Тема задачи") }}</span><select v-model="topic"><option value="">{{ t("Все темы") }}</option><option v-for="item in topics" :key="item" :value="item">{{ topicLabel(item) }}</option></select></label><label class="select-field"><AppIcon name="chart" :size="16" /><span class="sr-only">{{ t("Уровень готовности") }}</span><select v-model="level"><option value="all">{{ t("Любая готовность") }}</option><option v-for="item in levels" :key="item" :value="item">{{ readinessLabel(item) }}</option></select></label><label class="select-field"><AppIcon name="down" :size="16" /><span class="sr-only">{{ t("Сортировка задач") }}</span><select v-model="sort"><option value="desc">{{ t("Сначала готовые") }}</option><option value="asc">{{ t("Сначала требующие деталей") }}</option><option value="new">{{ t("Сначала новые") }}</option></select></label></div><div v-if="pending" class="state-panel" role="status"><span class="state-icon"><AppIcon name="compass" /></span><div><strong>{{ t("Загружаем каталог") }}</strong><p>{{ t("Ищем актуальные опубликованные задачи.") }}</p></div></div><div v-else-if="error" class="state-panel state-error" role="alert"><span class="state-icon"><AppIcon name="info" /></span><div><strong>{{ t("Не удалось загрузить каталог") }}</strong><button class="text-link" @click="refresh">{{ t("Попробовать снова") }}</button></div></div><template v-else><div class="results-toolbar"><span>{{ t("Найдено:") }} <strong>{{ filtered.length }}</strong></span><span>{{ t("Опубликованные задачи") }}</span></div><div v-if="filtered.length" class="task-grid"><TaskCard v-for="task in filtered" :key="task.id" :task="task" /></div><EmptyState v-else :title="t('Пока ничего не нашлось')" :description="t('Измените запрос или параметры фильтра.')" /></template></div></template>
